export default function getAllProducts() {
  return [
    {
      id: "CAM-001",
      slug: "sony-a7-iii",
      name: "Sony A7 III",
      category: "Mirrorless Camera",
      price: 25_000_000,
      stock: 50,
      imageUrl: "/assets/images/Sony-Alpha-1-001.jpg",
      description: `Sony A7 III adalah kamera mirrorless full-frame dengan performa unggulan untuk fotografer dan videografer profesional.`,
    },
    {
      id: "CAM-002",
      slug: "canon-eos-r6",
      name: "Canon EOS R6",
      category: "Mirrorless Camera",
      price: 32_000_000,
      stock: 30,
      imageUrl: `/assets/images/canon_eos_r6.jpg`,
      description: `Canon EOS R6 menawarkan stabilisasi gambar canggih dan kualitas video 4K yang luar biasa.`,
    },
    {
      id: "CAM-003",
      slug: "nikon-z9",
      name: "Nikon Z9",
      category: "Mirrorless Camera",
      price: 85_000_000,
      stock: 15,
      imageUrl: `/assets/images/Nikon_Z9.jpg`,
      description: `Nikon Z9 menawarkan kinerja tanpa cermin unggulan dengan sensor 45.7MP, perekaman video 8K, dan kemampuan autofokus canggih untuk kebutuhan profesional.`,
    },
    {
      id: "CAM-004",
      slug: "fujifilm-gfx100s",
      name: "Fujifilm GFX 100S",
      category: "Medium Format Camera",
      price: 100_000_000,
      stock: 5,
      imageUrl: `/assets/images/Fujifilm GFX100s.jpg`,
      description: `Fujifilm GFX 100S adalah kamera medium format dengan resolusi 102MP yang memberikan kualitas gambar luar biasa untuk fotografer landscape dan studio.`,
    },
    {
      id: "CAM-005",
      slug: "leica-m11",
      name: "Leica M11",
      category: "Rangefinder Camera",
      price: 120_000_000,
      stock: 8,
      imageUrl: `/assets/images/leica M11M10.jpg`,
      description: `Leica M11 menawarkan pengalaman fotografi tradisional dengan sensor full-frame 60MP, desain ikonik, dan teknologi digital modern untuk penggemar kamera premium.`,
    },
  ];
}
